### ISSUE TITLE
How does clojurescript work with a browser

### ISSUE THREAD

**Issue by pcn** [funcool/clojurescript-unraveled#103]
I'm interested in clojure+clojurescript.  The book so far is interesting, but it doesn't bridge the key gap of "how do I, as someone who doesn't currently do browser-based development in another language, approach clojurescript in the browser to accomplish a task".

In a CLI world, I can take a language and know where my inputs and outputs are (files, sockets, apis etc.).  What does one do with clojurescript in order to understand the inputs and outputs from the browser, and how does someone learning clojurescript bootstrap themselves into more knowledge?  E.g. in order to use D3.js, how would you know where data is coming from, how it is transformed in cljs, and how it could be displayed?  This sort of knowledge all seems to be a huge haze of "well, it depends" and having a treatment of this topic seems to be something that would get clojurescript a lot more use.

**Comment by jdeisenberg** [comment]
For a very brief overview, see section 6.1, Appendix A: Interactive development with Figwheel. Chapter 2 of Etudes for ClojureScript (http://catcode.com/etudes-for-clojurescript) goes into some detail about interacting with JavaScript as well.

**Comment by niwinz** [comment]
The book already includes a section for interactive development with figwheel and many other examples. This book does not intends to be a tutorial of a concrete framework/toolkit for web development; it is just a foundation for clojurescript language.
