### ISSUE TITLE
bootstrapped REPL integration

### ISSUE THREAD

**Issue by jaredly** [funcool/clojurescript-unraveled#112]
I've just made a (hopfully) portable [bootstrapped REPL](http://jaredforsyth.com/reepl/) w/ auto-complete, auto-documentation, and parinfer, and I'm looking for places that might benefit from a REPL :D 

this book is frequently recommended, and I imagine it would be a big value add to have a repl side-by-side w/ the text, especially if you could click a code sample & eval it right there.

I'd be happy to work on integration, but I thought I'd first ask if there's interest

**Comment by niwinz** [comment]
would be awesome!

**Comment by dialelo** [comment]
Awesome project, :+1: to your proposal of adding runnable examples in embeded REPLs, would love to see that.

**Comment by niwinz** [comment]
I'll close this issue because of no more news on this. If some one is interested in make the code snippets runnable, help is very welcome!
