### ISSUE TITLE
Minor error in the leap year example

### ISSUE THREAD

**Issue by wenxin-wang** [funcool/clojurescript-unraveled#116]
In the [current online version](https://funcool.github.io/clojurescript-unraveled/#first-project), It seems that the ```leap?``` predicate has wrong definition. According to wikipedia:

> if (year is not divisible by 4) then (it is a common year)
> else if (year is not divisible by 100) then (it is a leap year)
> else if (year is not divisible by 400) then (it is a common year)
> else (it is a leap year)

So ```leap?``` may be defined as
```
(defn leap?
  [year]
  (or (zero? (js-mod year 400))
      (and (pos? (js-mod year 100))
           (zero? (js-mod year 4)))))
```
Hope I didn't make a mistake.

**Comment by dialelo** [comment]
You're right, do you have time to open a PR? If not happy to edit it.

**Comment by wenxin-wang** [comment]
I'm glad to, please check the request, and see if I did it right.
