### ISSUE TITLE
Any updates on leanpub?

### ISSUE THREAD

**Issue by aadrian** [funcool/clojurescript-unraveled#135]
Hi,

Any updates on the Leanpub page of the book? 
```
This book is 75% complete
Updated 9 months Ago 
```

Thank you.

**Comment by niwinz** [comment]
Uploaded the latest version and marked as 100%. Thanks for the notice!

**Comment by aadrian** [comment]
> Uploaded the latest version and marked as 100%.

Maybe would help users more if the Leanpub link would be announced on the official mailing lists (Clojure and ClojureScript), Reddit, ClojureNews , etc. ? 

I'm sure quite a few Clojure users have missed that the book is ready :).

**Comment by niwinz** [comment]
This is a rolling release style book, and the current version have been published on gh-pages some time ago. Now the pdf, epub and mobi files are available for download but any one can generate themselves and the completeness and readyness  marker is very relative. The book at 75% was also complete but with less content. Now the book is marked as 100% complete but it does not means that it explains everything and in future I will add more content or upgrade the existing content.

In any case, thanks for the suggestion and feel free to publicizing it on  where you consider appropriate!

**Comment by aadrian** [comment]
> This is a rolling release style book

Than IMHO you should mark this one as 1st edition, and the next ones as further editions when they're ready (as what is planned to include one).
