### ISSUE TITLE
Link rot in  further reading

### ISSUE THREAD

**Issue by bugeb** [funcool/clojurescript-unraveled#136]
Link rot is `Études for ClojureScript`.  "http://catcode.com/etudes-for-clojurescript/toc.html" replace "http://catcode.com/etudes-for-clojurescript/toc01.html".

**Comment by niwinz** [comment]
Thanks!

**Comment by laurio** [comment]
Currently the "http://catcode.com/etudes-for-clojurescript/toc.html" seems to work and the "http://catcode.com/etudes-for-clojurescript/toc01.html" link does not.

**Comment by niwinz** [comment]
Fixed

**Comment by niwinz** [comment]
Thanks
