### ISSUE TITLE
About translation

### ISSUE THREAD

**Issue by t-cool** [funcool/clojurescript-unraveled#151]
Hi.

Would it be possible to translate clojurescript-unraveled into Japanese?  I started learning Clojure(Script) and this document is the best for beginners like me. 

I read the License and it seems that I need to keep the original English as it is so that I'll publish it online.  So I'd like to add Japanese translation bellow the original English sentences like this:
[https://t-cool.github.io/clojurescript-unraveled](https://t-cool.github.io/clojurescript-unraveled)
I won't claim copyright for my Japanese translation.
I'd appreciate your understanding.

**Comment by jdeisenberg** [comment]
I Am Not A Lawyer, but: I am looking at the license (https://creativecommons.org/licenses/by-sa/4.0/), and I don’t think you need to keep the original English. You need to keep a _link_ to it, as described in Section 3(a)(1)(a)(v), and that is also what Section 3(a)(2) seems to say.

In any case, you can get permission from the authors to make a Japanese-only version.

**Comment by t-cool** [comment]
@jdeisenberg 
Thank you for your advice! 

@niwinz 
I'll keep the original English and add Japanese translation below. 
When I finish its translation, I'll ask some seasoned clojurians to check my translation.
I guess it will take half a year to finish it, but it would be so valuable to Japanese readers.
It would be happy if you gave me a permission then.
I'd appreciate your understanding.

**Comment by jdeisenberg** [comment]
I'm not one of the main authors, so I can't give permission.

**Comment by niwinz** [comment]
As @jdeisenberg said, just keep a link to the original version! Feel free with the japanese only version. Nice to know that you found this book useful and nice to have the knowledge more accesible to japanese people.

**Comment by t-cool** [comment]
@niwinz 
Thank you for your understanding!
I'll try my best!

**Comment by t-cool** [comment]
@niwinz 

I'll finish translating the book soon.  I'll update the structure of the book and add some translations.  It'll take a few weeks to finish it.

Would it possible to print its Japanese translation as a paper book?  In Japan, there is an event to share self-published books among programming communities.  I'd like to print and share this book in the event.  It is not for commercial purpose, but for spreading the programming language community.  Last time, I joined Common Lisp community and published this book:
https://techbookfest.org/event/tbf06/circle/38170002

Clojurescript Unraveled is the best book ever to introduce ClojureScript. So I'd like to publish this book in the event and let Japanese developers know this book and ClojureScript.  I'll send all the money that I get from the book in the event to your leanpub account. 

I'd appreciate your understanding.

**Comment by niwinz** [comment]
Go ahead! :heart:

**Comment by niwinz** [comment]
Please, send me a copy when you finish it (if you can) (We can talk about shipping costs in private, I'm living in Europe)

**Comment by t-cool** [comment]
@niwinz 
Thank you for accepting my idea.
When I finish printing the book, I'll send a copy to the address you want.
I'll try my best!
