### ISSUE TITLE
make pdf on OSX 

### ISSUE THREAD

**Issue by t-cool** [funcool/clojurescript-unraveled#152]
I followed the steps here:
https://github.com/funcool/clojurescript-unraveled/issues/134

```
$ make pdf
mkdir -p docs/
asciidoctor -b docbook45 -a numbered -d book -a data-uri!  src/index.adoc -o docs/clojurescript-unraveled.xml
asciidoctor: FAILED: missing converter for backend 'docbook45'. Processing aborted.
  Use --trace for backtrace
make: *** [docbook] Error 1
```

I made a search on 'docbook45' and found this repo:
https://github.com/asciidoctor/asciidoctor-backends/tree/master/haml/docbook45

Could anyone advice me how to fix this issue?
I'd appreciate your help.

**Comment by nate** [comment]
This is what worked for me: https://github.com/funcool/clojurescript-unraveled/issues/153

**Comment by t-cool** [comment]
@nate 
Thanks a lot! 
I'll give a try in that way and let you know the result.

**Comment by t-cool** [comment]
I made it!
I made a search on my environment and found that I just need to change `docbook45` to `docbook` in the MakeFile as follows: 

```
docbook: setup
	asciidoctor -b docbook45 -a numbered -d book -a data-uri!  src/index.adoc -o dist/clojurescript-unraveled.xml
```

```
docbook: setup
	asciidoctor -b docbook -a numbered -d book -a data-uri!  src/index.adoc -o dist/clojurescript-unraveled.xml
```
