### ISSUE TITLE
Expand discussion of map and reduce

### ISSUE THREAD

**Issue by jdeisenberg** [funcool/clojurescript-unraveled#32]
I think the book needs at least one more example for both map and reduce that shows a user-defined function. (The problem here is that you know too much--you know that the higher-order-function can be user defined, but the beginner doesn't.) I'll be happy to add the examples and the wording.

**Comment by dialelo** [comment]
Definitely, :+1: go ahead if you want to improve the explanations of `map` and `reduce`.

**Comment by jdeisenberg** [comment]
Thank you for adding my commit to master.
