### ISSUE TITLE
More explicit instructions about file locations and project structure: Chapter 4 Getting started with compiler

### ISSUE THREAD

**Issue by NathanSmutz** [funcool/clojurescript-unraveled#50]
The target audience will need more hand holding on setting up that first project.
In Chapter 4: Getting Started with Compiler, there are no explicit instructions on where to put cljs.jar or build.clj.  
Having seen linengen projects, I might guess that these go above src (or at least build.clj might) but it's not obvious.  We probably want a little graphic or tree-chart showing where each file goes and probably a sidebar about project structure.

Also, capitalize Compiler in the section title.

**Comment by dialelo** [comment]
Great suggestions, thanks a lot!

**Comment by niwinz** [comment]
I'll try to review it this afternoon! Thanks!

**Comment by niwinz** [comment]
I think that is already revisited.
