### ISSUE TITLE
Clarification on Associative Destructuring example

### ISSUE THREAD

**Issue by shaunlebron** [funcool/clojurescript-unraveled#63]
With regards to:

```clj
(let [{tenth 10} (range 100)]
  tenth)
;; => 11
```

Maybe it should be clarified that this is equivalent to:

```clj
(get (apply hash-map (range 100)) 10)
;; => 11
```

and NOT equivalent to:

```clj
(get (vec (range 100)) 10)
;; => 10
```

**Comment by dialelo** [comment]
I'm afraid that the example is not very well chosen, the idea is to illustrate that any data type can act as a key and can be destructured. I'm going to change it to something simpler like:

```clojure
(let [{one 1} {0 "zero" 1 "one"}]
  one)
;; => "one"
```

Thanks for pointing this out!
