### ISSUE TITLE
Push updates to http://funcool.github.io/clojurescript-unraveled  ???

### ISSUE THREAD

**Issue by cloojure** [funcool/clojurescript-unraveled#97]
Hi - I was going to fix a typo but noticed it was already fixed in the source on GH.  Do we need a procedure to periodically push the most current version to http://funcool.github.io/clojurescript-unraveled  ?

Alan

**Comment by dialelo** [comment]
Hi @cloojure and thanks for the suggestion. I just pushed a new generated version of the HTML but I'm leaving this issue open so we implement automatic building and publishing of the book, probably through Travis CI.

**Comment by niwinz** [comment]
I'm personally not very convinced for automatic upload just because this can lead to broken uploads and this is something that I want to avoid.

I close the issue for this moment.
